version: 3

dotenv:
  - .env

tasks:
  install:
    desc: Install project dependencies
    aliases: [i]
    silent: true
    run: once
    sources:
      - package.json
      - yarn.lock
      - .yarnrc.yml
    cmds:
      - task: env
      - yarn install --immutable

  env:
    internal: true
    silent: true
    status:
      - test -f .env
    cmd: cp .env.example .env

  format:
    desc: Format the codebase
    aliases: [fmt]
    deps: [install]
    cmd: npx @biomejs/biome check --write .

  lint:
    desc: Lint the codebase
    deps: [install]
    cmds:
      - npx @biomejs/biome check .
      - npx svelte-kit sync
      - npx svelte-check --tsconfig ./tsconfig.json

  dev:
    desc: Run the development server
    deps: [install]
    cmd: npx vite dev
    env:
      NODE_ENV: development

  build:
    desc: Build the application
    deps: [install]
    cmd: npx vite build
    env:
      NODE_ENV: production

  serve:
    desc: Serve the application
    deps: [install]
    cmd: npx vite preview
    env:
      NODE_ENV: production

  test:unit:
    desc: Run unit tests
    aliases: [unit]
    deps: [install]
    cmd: npx vitest run --config vitest.unit.ts
    env:
      NODE_ENV: test

  test:unit:watch:
    aliases: [watch]
    desc: Run unit tests in watch mode
    cmd: npx vitest watch --config vitest.unit.ts --no-coverage
    env:
      NODE_ENV: test

  test:components:
    desc: Run component tests
    aliases: [component]
    deps: [install]
    cmd: npx vitest run --config vitest.components.ts
    env:
      NODE_ENV: test

  test:components:watch:
    desc: Run component tests in watch mode
    cmd: npx vitest watch --config vitest.components.ts
    env:
      NODE_ENV: test

  test:e2e:
    desc: Run end-to-end tests
    deps: [playwright, build]
    aliases: [e2e]
    cmd: npx playwright test
    env:
      NODE_ENV: production

  test:
    desc: Run the full acceptance test suite
    cmds:
      - task: lint
      - task: test:unit
      - task: test:components
      - task: test:e2e

  playwright:
    deps: [install]
    silent: true
    internal: true
    cmd: npx playwright install --with-deps
